SPINLIBS - Improve is_private_ip() function
spinpunch/spin-py-libs pull request #2
Opened 2022-08-05 12:47 UTC by The-Davis

Thanks to our new IP data querying system, I've noticed some known invalid IP addresses getting passed through as valid.

Based on the info at https://ipinfo.io/bogon, I converted our `is_private_ip()` function from a regex search to a known list of private CIDRs.  Rather than do both IPv4 and IPv6, I added a function to normalize IPv4 inputs to their IPv6 equivalents.

Since there are only 40 private IPv6 CIDRs, this just iterates low to high rather than doing a binary search

2022-08-05 12:48 UTC, The-Davis commented
Also, I ran a test against a random member of each CIDR and against a series of known good IPs. This functions correctly in a test environment.

2022-08-06 00:55 UTC, danmaas requested changes
Cool! See inline comments.

After testing this locally, here are the steps to get the gameservers to actually use it:
1. in this repo, create a new tag in Git with a new version number, e.g. 0.1.1. (the current version tag is 0.1.0)
2. update `gameserver/requirements.txt` and `loginserver/requirements.txt` to replace 0.1.0 with 0.1.1
3. on each machine, run `sudo python -m pip install -r requirements.txt` to grab the new version

2022-08-06 00:55 UTC, danmaas commented on spinlibs/SpinHTTP.py
> +from ipaddress import IPv6Address, IPv6Network
This means you'll need to add `ipaddress` to requirements.txt

2022-08-06 00:55 UTC, danmaas commented on spinlibs/SpinHTTP.py
> +    if '.' not in ip: return ip
to be clear, this case covers 1) IPv6 and 2) "unknown", right?

2022-08-06 00:55 UTC, danmaas commented on spinlibs/SpinHTTP.py
> +        hexified = str(hex(int(ip_chunk))).replace('0x','')
```
hexified = str(hex(int(ip_chunk)))[2:]
```
is probably a tiny bit more efficient

2022-08-06 00:55 UTC, danmaas commented on spinlibs/SpinHTTP.py
> +        normalized_ip = normalized_ip.replace('B%d' % i, hexified)
I feel like `normalized_ip` should be built up in one shot, like
```
normalized_ip = '2002:%s%s:%s%s::' % tuple(map(hexify, ip_chunks))
```

2022-08-06 00:55 UTC, danmaas commented on spinlibs/SpinHTTP.py
> +    if 'unknown' in ip: return True
to be safe I'd test against the literal `ip == 'unknown'` rather than using `in`. I can't imagine when we'd want to allow `XX)9sdfunknown---   ` as input to this function.

2022-08-06 00:55 UTC, danmaas commented on spinlibs/SpinHTTP.py
> +        if ip >= int(net[0]) and ip <= int(net[-1]):
You can write this more simply, using the "in" operator on IPv6Address:

```
# outside the function - pre-cache all these
private_ipv6_cidrs = map(IPv6Network, ['::/128','::1, .... ])

# inside the function
ip = IPv6Address(ip_normalize(ip))
return any(ip in cidr for cidr in private_ipv6_cidrs)
```

2022-08-06 23:52 UTC, The-Davis commented on spinlibs/SpinHTTP.py
> +from ipaddress import IPv6Address, IPv6Network
Added

2022-08-06 23:52 UTC, The-Davis commented on spinlibs/SpinHTTP.py
> +    if '.' not in ip: return ip
Correct

2022-08-06 23:53 UTC, The-Davis commented on spinlibs/SpinHTTP.py
> +    if 'unknown' in ip: return True
Done

2022-08-06 23:54 UTC, The-Davis commented on spinlibs/SpinHTTP.py
> +        if ip >= int(net[0]) and ip <= int(net[-1]):
Done

2022-08-06 23:57 UTC, The-Davis commented on spinlibs/SpinHTTP.py
> +        hexified = str(hex(int(ip_chunk))).replace('0x','')
Done

2022-08-07 00:17 UTC, The-Davis commented on spinlibs/SpinHTTP.py
> +        normalized_ip = normalized_ip.replace('B%d' % i, hexified)
Done

2022-08-07 00:21 UTC, merged